// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtaxTaBo3jacwzm30z9aFXdqG4QZTwXYI',
    appId: '1:653698123659:web:63832a5612dd4ccbc3118e',
    messagingSenderId: '653698123659',
    projectId: 'donutapp-flutter',
    authDomain: 'donutapp-flutter.firebaseapp.com',
    storageBucket: 'donutapp-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIazf5FEE00udzu6962wFYzIVjeEuH8IM',
    appId: '1:653698123659:android:655ee287fcdfe8c0c3118e',
    messagingSenderId: '653698123659',
    projectId: 'donutapp-flutter',
    storageBucket: 'donutapp-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoCBzmCIaNe6q3QO2fftVD-TneIQM1kQw',
    appId: '1:653698123659:ios:89ac0272470cc4cbc3118e',
    messagingSenderId: '653698123659',
    projectId: 'donutapp-flutter',
    storageBucket: 'donutapp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.donutApp2cGaxiola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoCBzmCIaNe6q3QO2fftVD-TneIQM1kQw',
    appId: '1:653698123659:ios:89ac0272470cc4cbc3118e',
    messagingSenderId: '653698123659',
    projectId: 'donutapp-flutter',
    storageBucket: 'donutapp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.donutApp2cGaxiola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtaxTaBo3jacwzm30z9aFXdqG4QZTwXYI',
    appId: '1:653698123659:web:9954d9df70b76ccec3118e',
    messagingSenderId: '653698123659',
    projectId: 'donutapp-flutter',
    authDomain: 'donutapp-flutter.firebaseapp.com',
    storageBucket: 'donutapp-flutter.firebasestorage.app',
  );
}
